export const costTypesList = [
    { value: 'Insumos', label: 'Insumos' },
    { value: 'Manutenção', label: 'Manutenção' },
    { value: 'Diesel', label: 'Diesel' },
    { value: 'Gasolina', label: 'Gasolina' },
    { value: 'Arla', label: 'Arla' },
    { value: 'Administrativo', label: 'Administrativo' },
    { value: 'Pessoal', label: 'Pessoal' },
    { value: 'Conservação', label: 'Conservação' },
    { value: 'Investimento', label: 'Investimento' },
    { value: 'Empréstimo', label: 'Empréstimo' },
    { value: 'Venda', label: 'Venda' },
    { value: 'Mão-de-obra', label: 'Mão-de-obra' },
    { value: 'Armazenagem', label: 'Armazenagem' },
    { value: 'Cantina', label: 'Cantina' },
    { value: 'Diversos', label: 'Diversos' },
    { value: 'Arrendo', label: 'Arrendo' },
    { value: 'Terceirizado', label: 'Terceirizado' },
    { value: 'Confinamento', label: 'Confinamento' }
  ];